language: node_js

node_js:
  - 6

sudo: required

dist: trusty

before_script:
  - npm install -g eslint
  - npm install -g istanbul
  - npm install -g mocha
  - npm install -g nyc

script:
  - npm test
  - npm run lint
